[project]
name = "2025"
version = "1.0.0"
description = "My solutions to Everybody Codes 2025"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.ruff.format]
quote-style = "single"
